openapi: 3.0.0
info:
  title: Minecraft Server API
  description: This API provides endpoints for interacting with and managing various aspects of a Minecraft server.
  version: 1.0.0
  contact:
    name: Dennis van den Brock
    email: dennisvandenbrock54@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
paths:
  /v1/players:
    get:
      summary: Retrieve the list of online players
      description: >
        This endpoint returns a list of all players who are currently online on the Minecraft server.
      tags:
        - Players
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A JSON array of online players
          content:
            application/json:
              schema:
                type: object
                properties:
                  onlinePlayers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the player
                          example: "Steve"
                        uuid:
                          type: string
                          description: The UUID of the player
                          example: "123e4567-e89b-12d3-a456-426614174000"
        '401':
          description: Unauthorized access - invalid or missing authentication key
        '500':
          description: Internal server error
  /v1/banned-players:
    get:
      summary: Retrieve the list of banned players
      description: >
        This endpoint returns a list of all banned players.
      tags:
        - Players
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A JSON array of banned players
          content:
            application/json:
              schema:
                type: object
                properties:
                  bannedPlayers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the player
                          example: "Steve"
                        uuid:
                          type: string
                          description: The UUID of the player
                          example: "123e4567-e89b-12d3-a456-426614174000"
        '401':
          description: Unauthorized access - invalid or missing authentication key
        '500':
          description: Internal server error
  /v1/offline-players:
    get:
      summary: Retrieve the list of offline players
      description: >
        This endpoint returns a list of all players who are currently offline on the Minecraft server.
      tags:
        - Players
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A JSON array of offline players
          content:
            application/json:
              schema:
                type: object
                properties:
                  offlinePlayers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the player
                          example: "Steve"
                        uuid:
                          type: string
                          description: The UUID of the player
                          example: "123e4567-e89b-12d3-a456-426614174000"
        '401':
          description: Unauthorized access - invalid or missing authentication key
        '500':
          description: Internal server error
