openapi: 3.0.0
info:
  title: Minecraft Server API
  description: This API provides endpoints for interacting with and managing various aspects of a Minecraft server.
  version: 1.0.0
  contact:
    name: Dennis van den Brock
    email: dennisvandenbrock54@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:

